export {
  CfnDemoPdfSourceService,
  CFN_DEMO_PDF_ALLOWLIST,
  LOCAL_PDF_SELECTION_LIMITS,
  buildCoverageSummary,
  buildPageRecord,
  detectExactCfnDemoPdfPacket,
  inspectLocalPdfFiles,
  inspectLocalPdfSelection,
  processLocalPdfSources,
  isExactCfnDemoPdfSelection,
  normalizeForSegmentMatch,
  pageIssueFor,
  processCfnDemoPdfSources,
  toSafeDocumentError,
  validateCfnDemoPdfSelection,
  validateLocalPdfSelection,
  type CfnDemoPdfPacketDetection,
  type CfnDemoDocumentServiceResult,
  type CfnDemoPdfSelectionIssue,
  type CfnDemoPdfSelectionIssueCode,
  type CfnDemoPdfSelectionValidation,
  type DocumentSafeError,
  type ExtractedPage,
  type LocalPdfInspection,
  type LocalPdfInspectionFile,
  type LocalPdfInspectionResult,
  type LocalDocumentRecord,
  type LocalPdfDocumentServiceResult,
  type LocalPdfSelectionIssue,
  type LocalPdfSelectionIssueCode,
  type LocalPdfSelectionValidation,
  type PdfDocumentLike,
  type PdfDocumentSource,
  type PdfJsRuntimeLike,
  type PdfLoadingTaskLike,
  type PdfPageLike,
  type VerifiedCfnDemoPdfFile,
  type ValidatedLocalPdfFile,
} from "./pdf-source-service";
