export {
  CfnDemoPdfSourceService,
  CFN_DEMO_PDF_ALLOWLIST,
  buildCoverageSummary,
  buildPageRecord,
  normalizeForSegmentMatch,
  pageIssueFor,
  processCfnDemoPdfSources,
  toSafeDocumentError,
  validateCfnDemoPdfSelection,
  type CfnDemoDocumentServiceResult,
  type CfnDemoPdfSelectionIssue,
  type CfnDemoPdfSelectionIssueCode,
  type CfnDemoPdfSelectionValidation,
  type DocumentSafeError,
  type ExtractedPage,
  type PdfDocumentLike,
  type PdfDocumentSource,
  type PdfJsRuntimeLike,
  type PdfLoadingTaskLike,
  type PdfPageLike,
  type VerifiedCfnDemoPdfFile,
} from "./pdf-source-service";
